### ISSUE TITLE
undefined symbol: iJIT_NotifyEvent error when starting training

### ISSUE THREAD

**Issue by YacineDeghaies** [cake-lab/Mobile-AR-Depth-Estimation#1]
I followed your instructions for training the ZoeDepth model on the nyu dataset and after I run  python train_mono.py -m zoedepth --pretrained_resource=""

I get this error. Did you have the same error ? Do you have any advice since you already trained the model again ? thank you

Error:
```
(zoe) gruenau9 deghaisa 49 ( ZoeDepth ) $ python train_mono.py -m zoedepth --pretrained_resource=""
Traceback (most recent call last):
  File "/vol/fob-vol3/mi20/deghaisa/code/ZoeDepth/train_mono.py", line 25, in <module>
    from zoedepth.utils.misc import count_parameters, parallelize
  File "/vol/fob-vol3/mi20/deghaisa/code/ZoeDepth/zoedepth/utils/misc.py", line 38, in <module>
    import torch
  File "/vol/fob-vol3/mi20/deghaisa/apps/mamba/envs/zoe/lib/python3.9/site-packages/torch/__init__.py", line 218, in <module>
    from torch._C import *  # noqa: F403
ImportError: /vol/fob-vol3/mi20/deghaisa/apps/mamba/envs/zoe/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent
(zoe) gruenau9 deghaisa 50 ( ZoeDepth ) $ 
```

**Comment by YacineDeghaies** [comment]
There's 2 solutions to this:
if requirements installed using mamba or conda, you have to downgrade mkl to mkl==2024.0.0

or simply install all requirements using pip
